[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Form settings
[forms]
  spam_protection = true

# Redirect rules for form submissions
[[redirects]]
  from = "/contact/thankyou"
  to = "/contact/thankyou"
  status = 200
